dist: trusty

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake pkg-config libglib2.0-dev libgpgme11-dev libgnutls28-dev uuid-dev libssh-gcrypt-dev libhiredis-dev

language: c

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install ; cd ..
